src/flexq/urls.py
from django.contrib import admin
from django.urls import (
    path,
    include,
)

urlpatterns = [
    path('admin/', admin.site.urls),

    path('polls/', include('polls.urls')),

    path("__debug__/", include("debug_toolbar.urls")),
]

src/polls/urls.py
from django.urls import path

from .views import (
    PollsView,
    PollView,
    QuestionView,
    StatisticView,
)

app_name = 'polls'
urlpatterns = [
    path("", PollsView.as_view(), name="list"),
    path("<int:poll_pk>/", PollView.as_view(), name='poll'),
    path("question/<int:question_pk>/", QuestionView.as_view(), name="question"),
    path("<int:poll_pk>/statistic/", StatisticView.as_view(), name="statistic"),
]

src/polls/models.py
from django.contrib.auth.models import User
from django.db import models
from django.db.models import (
    CheckConstraint,
    UniqueConstraint,
    Q,
    F,
)


class Poll(models.Model):
    title = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return 'Poll(pk={} title={})'.format(
            self.pk, self.title,
        )


class Question(models.Model):
    title = models.CharField(max_length=255, unique=True)

    poll = models.ForeignKey('Poll', on_delete=models.CASCADE)

    def __str__(self):
        return 'Question(pk={}, title={} poll_pk={})'.format(
            self.pk, self.title, self.poll_id,
        )


class Answer(models.Model):
    title = models.CharField(max_length=255, unique=True)

    def __str__(self):
        return 'Answer(pk={}, title={})'.format(
            self.pk, self.title,
        )


class AnswerQuestion(models.Model):
    answer = models.ForeignKey('Answer', on_delete=models.CASCADE)
    question = models.ForeignKey('Question', on_delete=models.CASCADE, related_name='questions')
    new_question = models.ForeignKey('Question', on_delete=models.CASCADE, null=True, blank=True,
                                     related_name='new_questions')

    class Meta:
        constraints = (
            UniqueConstraint(fields=('answer', 'question'), name='unique_answer_for_question'),
            UniqueConstraint(fields=('question', 'new_question'), name='unique_question_for_new_question'),
            CheckConstraint(check=~Q(question=F('new_question')), name="question_ne_new_question"),
        )

    def __str__(self):
        return 'AnswerQuestion(pk={}, answer_pk={} question_pk={} new_question_pk={})'.format(
            self.pk, self.answer_id, self.question_id, self.new_question_id,
        )


class UserResponse(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    answer_question = models.ForeignKey('AnswerQuestion', on_delete=models.CASCADE)

    # class Meta:
    #     constraints = (
    #         UniqueConstraint(fields=('user', 'answer_question'), name='unique_answer_question_for_user'),
    #     )

    def __str__(self):
        return 'Answer(pk={}, user_pk={} answer_question_pk={})'.format(
            self.pk, self.user_id, self.answer_question_id,
        )

src/polls/forms.py
from django import forms

from .models import AnswerQuestion


class MyModelChoiceField(forms.ModelChoiceField):
    def label_from_instance(self, obj: AnswerQuestion):
        return obj.answer.title


class AnswerQuestionForm(forms.Form):
    answer_question = MyModelChoiceField(queryset=None)

    def __init__(self, *args, **kwargs):
        queryset = (
            AnswerQuestion.objects
            .select_related('answer')
            .filter(question_id=kwargs.pop('question_id'))
        )
        super().__init__(*args, **kwargs)
        self.fields['answer_question'].queryset = queryset

src/polls/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import (
    HttpRequest,
)
from django.shortcuts import (
    render,
    redirect,
    get_object_or_404,
)
from django.views import View
from django.contrib import messages
from django.db.models.functions import DenseRank
from django.db.models import (
    F,
    Count,
    Window,
)

# Create your views here.
from .models import (
    Question,
    Poll,
    UserResponse,
    AnswerQuestion,
)
from .forms import AnswerQuestionForm


class PollsView(LoginRequiredMixin, View):

    def get(self, request: HttpRequest):
        polls = Poll.objects.all()
        ctx = {
            'polls': polls,
        }
        return render(request, 'polls/polls.html', ctx)


class PollView(LoginRequiredMixin, View):

    def get(self, request: HttpRequest, poll_pk: int):
        first_question = (
            AnswerQuestion.objects
            .select_related('question')
            .filter(question__poll__pk=poll_pk)
            .first()
        )
        if first_question:
            return redirect('polls:question', question_pk=first_question.question.pk)
        messages.add_message(request, messages.INFO, "For this polling doesn\'t exists questions.")
        return redirect('polls:list')


class QuestionView(LoginRequiredMixin, View):

    def get(self, request: HttpRequest, question_pk: int):
        question = get_object_or_404(Question, pk=question_pk)
        form = AnswerQuestionForm(question_id=question_pk)
        ctx = {
            'question': question,
            'form': form,
        }
        return render(request, 'polls/question.html', ctx)

    def post(self, request: HttpRequest, question_pk: int):
        question = get_object_or_404(Question, pk=question_pk)

        form = AnswerQuestionForm(request.POST, question_id=question_pk)
        if form.is_valid():
            user = request.user
            answer_question = form.cleaned_data['answer_question']

            UserResponse.objects.create(user=user, answer_question=answer_question)

            if not answer_question.new_question_id:
                messages.add_message(request, messages.INFO, 'You have completed the poll')
                return redirect('polls:statistic', poll_pk=question.poll_id)

            return redirect('polls:question', question_pk=answer_question.new_question_id)

        messages.add_message(request, messages.ERROR, form.errors)
        return redirect('polls:question', question_pk=question_pk)


class StatisticView(LoginRequiredMixin, View):
    def get(self, request: HttpRequest, poll_pk: int):
        poll = get_object_or_404(Poll, pk=poll_pk)

        total_participants = (
            UserResponse.objects
            .filter(answer_question__question__poll__pk=poll_pk)
            .values('user')
            .distinct()
            .count()
        )

        total_respondents_perc = (
            Question.objects
            .filter(poll__pk=poll_pk)
            .values('pk', 'title')
            .annotate(
                count_resp=Count('questions__userresponse__user__pk', distinct=True),
                perc=F('count_resp') * 100 / total_participants,
            )
        )

        rank_questions = (
            total_respondents_perc
            .annotate(rank=Window(expression=DenseRank(), order_by=F('count_resp').desc()))
        )

        total_respondents_on_every_question = (
            AnswerQuestion.objects
            .filter(question__poll__pk=poll_pk)
            .values('pk')
            .annotate(count_resp=Count('userresponse__user', distinct=True))
            .annotate(perc=F('count_resp') * 100 / Count('question'))
        )

        ctx = {
            'poll': poll,
            'total_participants': total_participants,
            'total_respondents_perc': total_respondents_perc,
            'rank_questions': rank_questions,
            'total_respondents_on_every_question': total_respondents_on_every_question,
        }

        return render(request, 'polls/statistic.html', ctx)

src/polls/templates/polls/layout.html
<!DOCTYPE html>
<html lang="en" data-bs-theme="dark">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    <title>Title</title>
</head>
<body>
{% if messages %}
{% for message in messages %}
    <div class="messages alert alert-{% if message.tags %}{{ message.tags }}{% endif %}" role="alert">
        {{ message }}
    </div>
{% endfor %}
{% endif %}

{% block content %}{% endblock %}
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
</body>
</html>

src/polls/templates/polls/polls.html
{% extends "polls/layout.html" %}
{% block content %}
<h1>Polls</h1>
<ul class="list-group">
    {% for poll in polls %}
    <li class="list-group-item"><a href="{% url 'polls:poll' poll.pk %}">{{ poll.title }}</a></li>
    {% endfor %}
</ul>
{% endblock %}

src/polls/templates/polls/question.html
{% extends "polls/layout.html" %}
{% block content %}
{{ question.title }}
<form method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock %}

src/polls/templates/polls/statistic.html
{% extends "polls/layout.html" %}
{% block content %}
<h1>Polling: {{ poll.title }}</h1>

<h3>Total participants: {{ total_participants }}</h3>

<table class="table caption-top">
    <caption>Count Respondents and % from all Respondents</caption>
    <thead>
    <tr>
        <th scope="col" class="th1">PK Question</th>
        <th scope="col" class="th2">Title</th>
        <th scope="col" class="th3">Count Respondents</th>
        <th scope="col" class="th4">% from all Respondents</th>
    </tr>
    </thead>
    <tbody>
    {% for q in total_respondents_perc %}
    <tr>
        <td>{{ q.pk }}</td>
        <td>{{ q.title }}</td>
        <td>{{ q.count_resp }}</td>
        <td>
            <div class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="75"
                 aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{ q.perc }}%">
                    {{ q.perc }}%
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<table class="table caption-top">
    <caption>Runk Questions by Respondents</caption>
    <thead>
    <tr>
        <th scope="col" class="th1">PK Question</th>
        <th scope="col" class="th2">Runk</th>
    </tr>
    </thead>
    <tbody>
    {% for q in rank_questions %}
    <tr>
        <td>{{ q.pk }}</td>
        <td>{{ q.rank }}</td>
    </tr>
    {% endfor %}
    </tbody>
</table>

<table class="table caption-top">
    <caption>Count Respondents by Variable Answers</caption>
    <thead>
    <tr>
        <th scope="col" class="th1">PK Variable</th>
        <th scope="col" class="th2">Count Respondents</th>
        <th scope="col" class="th3">% from Count related Questions</th>
    </tr>
    </thead>
    <tbody>
    {% for q in total_respondents_on_every_question %}
    <tr>
        <td>{{ q.pk }}</td>
        <td>{{ q.count_resp }}</td>
        <td>
            <div class="progress" role="progressbar" aria-label="Animated striped example" aria-valuenow="75"
                 aria-valuemin="0" aria-valuemax="100">
                <div class="progress-bar progress-bar-striped progress-bar-animated" style="width: {{ q.perc }}%">
                    {{ q.perc }}%
                </div>
            </div>
        </td>
    </tr>
    {% endfor %}
    </tbody>
</table>
<div class="d-grid gap-2 d-md-flex justify-content-md-start">
    <a class="btn btn-dark me-md-2" type="button" href="{% url 'polls:list' %}">
        <contents>< Reverse to Polls</contents>
    </a>
</div>
{% endblock %}